# Travis CI is only used to check the lesson and is not involved in its deployment
dist: xenial  # Ubuntu 16.04 (required for python 3.7)
language: python
python: 3.7
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - rvm default
  - gem install json kramdown jekyll bundler
install:
  - pip install -U pyyaml
script:
  - make lesson-check-all
  - make --always-make site
